---
- hosts: web
  name: Configures apache on all the app servers
  become: yes
  roles:
    - apache 

  tasks:
    - name: gather apache version
      shell: "{{ apache_service}} -v|grep version|awk '{print $3}'|cut -f2 -d'/'"
      register: result

    - name: create dynamic group with apache version
      group_by: 
        key: apache_{{ result.stdout }}

- hosts: apache_2.2.15
  name: Do this on apache 2.2.15 machines
  become: yes
  tasks:
    - debug: 
        msg: "This task will occur on the 2.2.15 machines"

- hosts: apache_2.4.6
  name: Do this on apache 2.4.6 machines
    tasks:
    - debug: 
        msg: "This task will occur on the 2.4.6 machines."
