# In keeping things simple, this example assumes the epel repo is enabled on each node
---
- hosts: web
  name: install and start nginx with wsgi
  become: yes
  vars:
    nginx_packages:
      - nginx
      - python-pip
      - python-devel
      - gcc
    nginx_test_message: This is a test message
    nginx_keepalive_timeout: 115

  tasks:
    - name: install nginx packages
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ nginx_packages }}"
      notify: restart nginx service

    - name: install uwsgi
      pip:
        name: uwsgi
        state: present
      notify: restart nginx service

    - name: copy default.conf
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        backup: yes
      notify: restart nginx service

    - name: copy index.html
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html

    - name: start nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    # smoke test that nginx came up and is serving home page
    - name: check for proper response
      uri:
        url: http://localhost/
        return_content: yes
      register: response
      until: 'nginx_test_message in response.content'
      retries: 10
      delay: 1

  handlers:
    - name: restart nginx service
      service:
        name: nginx
        state: restarted
        enabled: yes
