---
# tasks file for apache

- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: include_vars

# OS specific package installations
- include: "{{ ansible_os_family }}.yml"

- name: create sites directories
  file: 
    path: "{{ item }}"
    state: directory
  with_items: "{{ apache_dirs }}"

- name: copy index.html
  template: 
    src: index.html.j2 
    dest: "{{ apache_docroot }}/index.html"

- name: copy httpd.conf
  template: 
    src: httpd.conf-{{ ansible_os_family }}.j2 
    dest: "{{ apache_config }}"
  notify: restart apache

- name: start and enable apache service
  service: 
    name: "{{ apache_service }}"
    state: started 
    enabled: yes
  tags: service


