- name: stop firewalld
  service:
    name: firewalld
    state: stopped
  ignore_errors: yes

- name: install packages (Red Hat)
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"
  tags: package
