---
- name: Update cache
  apt: 
    update_cache: yes 
    cache_valid_time: 3600
  tags: package

- name: install commons packages (Debian )
  apt: 
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"
