---
# tasks file for common
- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: include_vars

# OS specific package installations
- include: "{{ ansible_os_family }}.yml"

- name: include users
  include_vars: users.yml

- name: create users
  user: 
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    comment: "{{ item.comment }}"
  with_items: "{{ users }}"
