- name: install epel
  yum: 
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm 
    state: present

- name: install commons packages (Red Hat)
  yum: 
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: stop firewalld 
  service: 
    name: firewalld
    state: stopped

